# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node v16
        uses: actions/setup-node@v1
        with:
          version: 16.x
      - name: Install NPM packages
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: dist/conditional-logic-repeater.js
      #     asset_name: conditional-logic-repeater.js
      #     tag: ${{ github.ref }}
      #     overwrite: true
      #     body: "This is my release text"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: Fhwang0926/upload-release-asset@v1.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_name: .dist/conditional-logic-repeater.js
          asset_label: latest
