# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Node.js 16
      uses: actions/setup-node@v1
      with:
        version: 16.x
    - run: npm ci
    - run: npm run build
    - name: Create release
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/conditional-logic-repeater.js"
        bodyFile: "body.md"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
